const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
let code=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('function logout()'));
const nodes=new Map(),storage=new Map(),timers=new Map();let timer=0;
const noop=()=>{};
const canvas=new Proxy({},{get:()=>noop,set:()=>true});
function el(id){if(!nodes.has(id)) nodes.set(id,{id,hidden:false,value:'',textContent:'',innerHTML:'',dataset:{},style:{setProperty:noop},classList:{add:noop,remove:noop,toggle:noop},addEventListener:noop,setAttribute:noop,remove(){this.removed=true},close(){this.open=false},querySelector:el,querySelectorAll:()=>[],appendChild:noop,getBoundingClientRect:()=>({width:400,height:400,left:0,top:0}),getContext:()=>canvas});return nodes.get(id)}
const sandbox={console,window:{matchMedia:()=>({matches:false}),ECOS_CONFIG:{}},document:{documentElement:el('html'),getElementById:el,querySelector:el,querySelectorAll:()=>[],createElement:el,addEventListener:noop,body:el('body')},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},performance:{now:()=>1000},setTimeout:f=>{timers.set(++timer,f);return timer},clearTimeout:i=>timers.delete(i),setInterval:noop,clearInterval:noop,requestAnimationFrame:noop,navigator:{},location:{protocol:'http:'},crypto:require('crypto').webcrypto,TextEncoder};sandbox.window.addEventListener=noop;
code=code.replace('/* ---------- boot ---------- */',`window.qa = {fresh,logout,doLogin,cloudSave,syncCloud,tick,attack,dps,clickDmg,sbBack,heroPower,heroCost,buyHero,heroAvailable,soulGain,rebirth,kill,hydrate,offline,useSkill,unlockSkill,skillUnlocked,get S(){return S},get B(){return B},get ACC(){return ACC},get ready(){return cloudReady},get undo(){return undoSave},get epoch(){return sessionEpoch}, setBack(b){BACK=b}, seed(s){S=s;B=calcBon(); ACC={id:'alpha',name:'Alpha'};cloudReady=true;undoSave=JSON.stringify(s); combo=20;comboT=3; S.enemy={hp:10,max:10};},setReady(v){cloudReady=v}}; return;\n/* ---------- boot ---------- */`);
vm.runInNewContext(code,sandbox); const q=sandbox.window.qa;
const back={kind:'test',logout:noop,stopRank:noop,rank:noop,save:async()=>{},login:async()=>({acc:{id:'beta',name:'Beta'},save:null})};q.setBack(back);
(async()=>{
let s=q.fresh();s.gold=1e8;q.seed(s);
q.buyHero(1);assert.equal(q.S.heroes[1],0);assert.equal(q.S.gold,1e8);
q.S.maxZone=4;q.buyHero(1);assert.equal(q.S.heroes[1],1);assert(q.S.gold<1e8);
assert(q.heroPower(0,100)<0.6*100*16/4);assert(q.heroPower(0,101)>q.heroPower(0,100));
assert(q.heroPower(0,200)/q.heroPower(0,100)<=2.001);
console.log('PASS companions require current-run zones; mastery has no exponential stacking');
s=q.fresh();s.rebirths=2;s.soul.start=40;s.zone=s.maxZone=81;q.seed(s);
assert.equal(q.soulGain(),0);q.rebirth();assert.equal(q.S.rebirths,2);
q.S.runBossMax=16;assert(q.soulGain()>0);q.rebirth();assert.equal(q.S.rebirths,3);assert.equal(q.S.runBossMax,0);assert.equal(q.soulGain(),0);
console.log('PASS shortcut cannot grant souls or chain rebirths; boss proof resets every run');
s=q.fresh();s.zone=12;s.stage=10;s.gold=0;s.level=1;q.seed(s);q.S.enemy={hp:0,max:100,boss:true,name:'QA',icon:'X'};q.kill();assert.equal(q.S.runBossMax,12);assert(q.soulGain()>0);
console.log('PASS defeating the actual required boss grants rebirth eligibility');
s=q.hydrate({zone:81,maxZone:81,rebirths:3});q.seed(s);assert.equal(q.S.runBossMax,0);assert.equal(q.soulGain(),0);assert.deepEqual(Array.from(q.S.unlockedSkills),[]);
s=q.fresh();s.rebirths=3;s.maxZoneEver=30;s.stats.bosses=60;s.souls=25;q.seed(s);
q.S.stats.bosses=59;assert.equal(q.unlockSkill('eclipse'),false);assert.equal(q.S.souls,25);q.S.stats.bosses=60;
assert.equal(q.unlockSkill('eclipse'),true);assert.equal(q.S.souls,0);assert.equal(q.unlockSkill('eclipse'),false);assert(q.skillUnlocked('eclipse'));
el('start').hidden=true;q.S.enemy={hp:100,max:100,boss:false};q.useSkill('eclipse');assert.equal(q.S.sk.eclipse,0);
q.S.enemy.boss=true;q.useSkill('eclipse');assert.equal(q.S.buff.eclipse,8);assert(q.S.sk.eclipse>0);q.S.runBossMax=18;q.rebirth();assert(q.skillUnlocked('eclipse'));assert.equal(q.S.buff.eclipse,0);
q.logout();assert.equal(q.skillUnlocked('eclipse'),false);assert.equal(q.S.buff.eclipse,0);
console.log('PASS Eclipse requirements/cost, repeat unlock prevention, boss-only activation, rebirth persistence and logout isolation');
s=q.fresh();s.level=15;q.seed(s);el('start').hidden=true;q.S.enemy={hp:100,max:100,boss:false};q.useSkill('time');assert.equal(q.S.sk.time,0);
q.S.enemy.boss=true;q.S.bossT=5;q.useSkill('time');assert.equal(q.S.bossT,20);q.useSkill('time');assert.equal(q.S.bossT,20);
q.useSkill('fury');assert.equal(q.S.buff.fury,10);q.S.buff.fury=7;q.useSkill('fury');assert.equal(q.S.buff.fury,7);
console.log('PASS skills do not consume cooldown on invalid targets or activate twice');
s=q.fresh();s.heroes[0]=100000;s.lastSeen=Date.now()-3600000;q.seed(s);q.offline();assert(q.S.gold<=21*3601*0.22*0.5);assert(q.S.gold>0);
console.log('PASS offline income capped by current zone despite oversized legacy companions');
})().catch(e=>{console.error(e);process.exitCode=1});
